sudo: required
dist: bionic
language: python
cache: pip
python:
  - "2.7"
env:
  matrix:
    bash ./script/create_matrix.sh
    #- TF_VERSION="1.8.*"
install:
  - pip install -q "tensorflow==$TF_VERSION"
  - pip install -q -U numpy
  - pip install matplotlib
  - pip install opencv-python
script:
  # Check import
  - python -c 'import tensorflow as tf; print(tf.__version__)'

  # Run tests
  - bash test.sh
 
