sudo: required
dist: bionic
language: python
python: # Only two versions for now
  - "2.7"

env:
  matrix:
    -TF_VERSION="1.*"
# command to install dependencies
install:
  - ./script/pip_install.sh
  #- pip install -r requirements.txt
script:
  - bash test.sh
 
